config/routes.rb
Rails.application.routes.draw do
  resources :students
  
  root 'students#index'
  
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end


  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end


  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        redirect_to students_path
      else
        render :new

      end
    end
  end

  def update
    respond_to do |format|
      if @student.update(student_params)
        redirect_to @student
      else
        render :edit 
      end
    end
  end


  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student removed from database.' }
    end
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end


    def student_params
      params.require(:student).permit(:Name, :Gender, :Weight, :Height, :Colour, :GPA, :PrimaryCampus, :Faculty)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<h1> FORM</h1>

<%= form_for(@student) do |f| %>


  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>

  <div class="field">
    <%= f.label :Gender %><br>
     <%= f.text_field :Gender %>
  </div>
  
   <div class="field">
    <%= f.label :'Weight in Pounds' %><br>
    <%= f.text_field :Weight %>
  </div>
  <div class="field">
    <%= f.label :'Height in Centimetres' %><br>
    <%= f.text_field :Height %>
  </div>
  <div class="field">
    <%= f.label :Colour %><br>
    <%= f.text_field :Colour %>
  </div>
  
<div class="field">
    <%= f.label :'GPA' %><br>
    <%= f.text_field :GPA %>
  </div>
  
  
  
  
  <br> 
  
  <div class="actions">
    <%= f.submit 'Update Student' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Student Database</h1>

<table style="width:100%">
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Colour</th>
      <th>GPA</th>
      <th>Campus</th>
      <th>Faculty</th>

    </tr>
  </thead>
  <tbody>

  </tbody>
</table>


<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gender</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Colour</th>
      <th>Gpa</th>
      <th>Campus</th>
      <th>Faculty</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.Name %></td>
        <td><%= student.Gender %></td>
        <td><%= student.Weight %></td>
        <td><%= student.Height %></td>
        <td><%= student.Colour %></td>
        <td><%= student.GPA %></td>
        <td><%= student.PrimaryCampus %></td>
        <td><%= student.Faculty %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Cancel', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.Name %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @student.Gender %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @student.Weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @student.Height %>
</p>

<p>
  <strong>Colour:</strong>
  <%= @student.Colour %>
</p>

<p>
  <strong>Gpa:</strong>
  <%= @student.GPA %>
</p>

<p>
  <strong>Campus:</strong>
  <%= @student.PrimaryCampus %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @student.Faculty %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>